import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nexa Bank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
      <Toaster
     position="top-right"
     reverseOrder={false}
     gutter={10}
     toastOptions={{
     duration: 3000,
     style: {
      borderRadius: "14px",
      background: "#ffffff",
      color: "#111827",
      fontWeight: "600",
    },
    success: {
      iconTheme: {
        primary: "#16a34a",
        secondary: "#ffffff",
      },
    },
    error: {
      iconTheme: {
        primary: "#dc2626",
        secondary: "#ffffff",
      },
    },
  }}
/>
      </body>
    </html>
  );
}
